# Generated by Django 6.1.1 on 2026-09-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.PositiveIntegerField(default=20, help_text='Auto-calculated lead score (0-100)'),
        ),
    ]
