# Generated by Django 6.1.1 on 2026-09-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
    ]
