# Generated by Django 6.1.1 on 2026-09-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='probability',
            field=models.PositiveIntegerField(default=10, help_text='Auto-set based on stage'),
        ),
    ]
