# Generated by Django 6.1.1 on 2026-09-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_probability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Deals'},
        ),
    ]
