# Generated by Django 6.1.1 on 2026-09-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'Customers'},
        ),
    ]
