# Generated by Django 6.1.1 on 2026-09-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date'], 'verbose_name_plural': 'Tasks'},
        ),
    ]
